### ISSUE TITLE
Error connecting to remote host from macOS

### ISSUE THREAD

**Issue by tdietel** [Xpra-org/xpra#3222]
I have some problems running Xpra on macOS. After being unable to run 4.2.1, I upgraded to the beta version 4.3.

When I click on "Connect", I get window "Error creating launcher form". There is a Python traceback, which I cannot copy&paste, but in the end it says "Icon 'bugs' not present in theme Adwaita (0)"

I then tried the "Start" button, entered remote host info and clicked "Start & Attach". I started Xpra from a terminal, and there I can see the exception:
```
splash=True (<class 'bool'>) - not None (<class 'NoneType'>)
mousewheel=on (<class 'str'>) - not invert-x (<class 'str'>)
xpra main error:
Traceback (most recent call last):
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/scripts/main.py", line 133, in main
    return run_mode(script_file, cmdline, err, options, args, mode, defaults)
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/scripts/main.py", line 414, in run_mode
    return do_run_mode(script_file, cmdline, error_cb, options, args, mode, defaults)
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/scripts/main.py", line 424, in do_run_mode
    return run_remote_server(error_cb, options, args, mode, defaults)
TypeError: run_remote_server() missing 2 required positional arguments: 'mode' and 'defaults'
```

The remote system is running CentOS 7, and I only found Xpra 3.1 for that OS, so this might be the issue.

**Comment by tdietel** [comment]
I just tried to start a local session, but the radio button in the "Start" panel is greyed out.

**Comment by totaam** [comment]
Sorry about that, that had already been fixed in cff50de835e9392ff30ccb11dcdd645973b079e3 but the MacOS builds were out of date.

Just to be clear, this only affected _remote-start-and-connect_ not _connecting_ alone.
So you could still start your session remotely and attach to it with `xpra attach`.

I any case, I've posted a new beta just now. There's also a 4.2.2 pre-release version from the stable branch.

> `not present in theme Adwaita (0)`

You can safely ignore any warnings about themes and icons.

> The remote system is running CentOS 7, and I only found Xpra 3.1 for that OS, so this might be the issue.

No that's fine: 3.x is the only branch that still supports Python2 (ie: CentOS 7)
https://github.com/Xpra-org/xpra/wiki/Versions

> I just tried to start a local session, but the radio button in the "Start" panel is greyed out.

You cannot start local sessions on macos.

**Comment by tdietel** [comment]
Thank you for your help. I have now tried the latest beta, and managed to get it running with the command line.

However, when I connect from the GUI, I still get an error message.
```
(Xpra:48583): Gtk-CRITICAL **: 11:48:24.032: gtk_window_add_accel_group: assertion 'GTK_IS_WINDOW (window)' failed
2021-07-27 11:48:24,187 Xpra GTK3 client version 4.3-r29519 (gfe9e6d878) 64-bit
2021-07-27 11:48:24,216  running on Mac OS X 10.16
2021-07-27 11:48:26,962 GStreamer version 1.18.4 for Python 3.9.5 64-bit
2021-07-27 11:48:27,004 created unix domain socket '/Users/tom/.xpra/clients/xenon.local-48583'
2021-07-27 11:48:27,098 OpenGL_accelerate module loaded
2021-07-27 11:48:27,121 Using accelerated ArrayDatatype
2021-07-27 11:48:27,617 OpenGL enabled with AMD Radeon Pro 5300M OpenGL Engine
2021-07-27 11:48:27,769 Connected (version 2.0, client OpenSSH_7.4)
2021-07-27 11:48:27,921 Authentication (publickey) successful!

(Xpra:48583): Gtk-CRITICAL **: 11:48:28.284: gtk_window_add_accel_group: assertion 'GTK_IS_WINDOW (window)' failed
2021-07-27 11:48:28,288  SSH: 'xpra initialization error:'
2021-07-27 11:48:28,288  SSH: ' no such option: --splash'
2021-07-27 11:48:28,293 SSH EOF on stderr of run-xpra
2021-07-27 11:48:28,320  keyboard settings: layout=us
2021-07-27 11:48:28,325  desktop size is 3712x1200:
2021-07-27 11:48:28,326   xenon.local (862x538 mm - DPI: 109x57)
2021-07-27 11:48:28,326     monitor 1 1920x1200 at    0x0    (518x324 mm - DPI: 94x94) workarea: 1920x1175 at    0x25
2021-07-27 11:48:28,326     1 1792x1120 at 1920x80   (344x214 mm - DPI: 132x133) workarea: 1792x1095 at 1920x105

(Xpra:48583): Gtk-WARNING **: 11:48:28.354: Theme file for hicolor has no name

(Xpra:48583): Gtk-WARNING **: 11:48:28.354: Theme file for hicolor has no directories
2021-07-27 11:48:28,369 Error: failed to receive anything, not an xpra server?
2021-07-27 11:48:28,369   could also be the wrong protocol, username, password or port
2021-07-27 11:48:28,369   or the session was not found
2021-07-27 11:48:28,369 Connection lost
2021-07-27 11:48:28,386 removing unix domain socket '/Users/tom/.xpra/clients/xenon.local-48583'
CONNECTION_LOST, reconnecting
args=['xpra', 'attach', '--exit-with-client=False', '--exit-with-children=True', '--start-child=/usr/bin/xterm', '--attach=True', '--splash=True', '--mousewheel=on', 'ssh://tdietel@alicetrd.phy.uct.ac.za:22/Main']
xpra main error:
Traceback (most recent call last):
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/scripts/main.py", line 135, in main
    return run_mode(script_file, cmdline, err, options, args, mode, defaults)
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/scripts/main.py", line 416, in run_mode
    return do_run_mode(script_file, cmdline, error_cb, options, args, mode, defaults)
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/scripts/main.py", line 426, in do_run_mode
    return run_remote_server(script_file, cmdline, error_cb, options, args, mode, defaults)
  File "/Applications/Xpra.app/Contents/Resources/lib/python/xpra/scripts/main.py", line 2493, in run_remote_server
    os.execv(args[0], args)
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by totaam** [comment]
Ah, gotcha: `no such option: --splash` is a compatibility problem with 3.x The commit above should fix that. (and it also affected 4.2.2-RC, also fixed now)

So you're using the start gui in ssh mode to a centos7 server from a macos client, right?
I had not tested this particular combination for a while it seems, sorry. I have tested it this time!

> > `not present in theme Adwaita (0)`
> >
> You can safely ignore any warnings about themes and icons.
>
I was wrong about this one too...
I have reproduced it and it does prevent the dialog from showing up.

**Comment by totaam** [comment]
Works for me(tm).

There are updated beta builds with those fixes in the [MacOS beta area](https://xpra.org/beta/MacOS/)

Feel free to re-open if I have missed something.
