### ISSUE TITLE
Error parsing icon data for notification

### ISSUE THREAD

**Issue by jdstroy** [Xpra-org/xpra#3366]
xpra server reported this error (appears to be from Firefox posting a "Toast" style notification for the Element Matrix client):
```
2021-11-27 05:32:45,525 Error parsing icon data for notification:
2021-11-27 05:32:45,525  a bytes-like object is required, not 'list'
```
Server:

xpra v4.3-r30545 (g5d34d0592)

Client:
`v4.3-r30469 (g1f7f5b2af)`

**Comment by totaam** [comment]
If this is reproducible, please post the log output when running the client with `-d notify`.

**Comment by totaam** [comment]
Not heard back..

**Comment by jdstroy** [comment]
My apologies; I got a bit busy over the winter, and this fell off my plate.  Here's the output that I logged with `-d notify`:


```
2022-04-09 19:12:20,999 Xpra GTK3 client version 4.2.3-r3 64-bit
2022-04-09 19:12:21,077  running on Microsoft Windows 10
2022-04-09 19:12:28,623 GStreamer version 1.18.5 for Python 3.9.7 64-bit
2022-04-09 19:12:28,675 make_notifier() notifier classes: [<class 'xpra.platform.win32.win32_notifier.Win32_Notifier'>, <class 'xpra.gtk_common.gtk_notifier.GTK_Notifier'>, <class 'xpra.client.gtk3.gtk3_notifier.GTK3_Notifier'>]
2022-04-09 19:12:28,683 using notifier=<xpra.platform.win32.win32_notifier.Win32_Notifier object at 0x0000019cfb3b7f10>
2022-04-09 19:12:29,351 created named pipe 'Xpra\4844'
2022-04-09 19:12:29,814 keyboard layout code 0x409
2022-04-09 19:12:29,821 identified as 'United States - English' : us
2022-04-09 19:12:30,198 OpenGL_accelerate module loaded
2022-04-09 19:12:30,324 Using accelerated ArrayDatatype
2022-04-09 19:12:32,990 Warning: vendor 'Intel' is greylisted,
2022-04-09 19:12:32,990  you may want to turn off OpenGL if you encounter bugs
2022-04-09 19:12:33,557 OpenGL accelerate missing: numpy_formathandler
2022-04-09 19:12:35,884 OpenGL enabled with Intel(R) UHD Graphics 605
2022-04-09 19:12:37,322 Connected (version 2.0, client OpenSSH_8.2p1)
2022-04-09 19:12:37,740 loaded RSA private key from 'C:\Users\REDACTED/.ssh\id_rsa'
2022-04-09 19:12:37,887 Authentication (publickey) successful!
2022-04-09 19:12:38,646  keyboard settings: layout=us
2022-04-09 19:12:38,658  desktop size is 1920x1080 with 1 screen:
2022-04-09 19:12:38,658   Default (406x228 mm - DPI: 120x120) workarea: 1920x1020
2022-04-09 19:12:38,658     Digital Flat Panel (1024x768 60Hz) (344x194 mm - DPI: 142x141)
2022-04-09 19:12:42,077 enabled remote logging
2022-04-09 19:12:42,109 Xpra X11 seamless server version 4.4-r30923 64-bit
2022-04-09 19:12:42,109  running on Linux Ubuntu 20.04 focal
2022-04-09 19:12:42,140 Attached to ssh://REDACTED@REDACTED/21
2022-04-09 19:12:42,169  (press Control-C to detach)


(Xpra_cmd.exe:4844): Pango-WARNING **: 19:12:45.749: couldn't load font "DejaVu Serif Not-Rotated 59.796875", falling back to "Sans Not-Rotated 59.796875", expect ugly output.

(Xpra_cmd.exe:4844): Pango-WARNING **: 19:12:45.765: couldn't load font "URW Bookman L Not-Rotated 52.76171875", falling back to "Sans Not-Rotated 52.76171875", expect ugly output.
2022-04-09 19:12:46,069 audio playback using 'opus' audio codec
2022-04-09 19:12:46,147 running, 7 windows
2022-04-09 19:12:47,107 Warning: the audio playback process has failed to start
2022-04-09 19:13:14,718 _process_notify_show(['notify_show', b'unix:abstract=/tmp/dbus-jsivYu .. ', b'Activate'), {b'desktop-entry': b'Firefox'}]) notifier=<xpra.platform.win32.win32_notifier.Win32_Notifier object at 0x0000019cfb3b7f10>, server_notifications=True
2022-04-09 19:13:14,718 notification actions=(b'default', b'Activate'), hints={b'desktop-entry': b'Firefox'}
2022-04-09 19:13:14,718 get_tray_window(Firefox)=Tray(0:Xpra)
2022-04-09 19:13:14,718 show_notify(..) using gtk fallback, GTK_NOTIFIER=False, tray=Tray(0:Xpra), getHWND=<bound method Win32Tray.getHWND of Tray(0:Xpra)>, actions=(b'default', b'Activate')
2022-04-09 19:13:14,733 monitors=1
2022-04-09 19:13:14,733 first monitor dimensions: 1920x1080
2022-04-09 19:13:14,733 our reduced dimensions: 1900x1016
2022-04-09 19:13:14,733 Popup(<xpra.gtk_common.gtk_notifier.GTK_Notifier object at 0x0000019c81e47bb0>, 51, 'REDACTED (IRC)', '[notify]', (b'default', b'Activate'), None, -1, False)
2022-04-09 19:13:14,910 get_x(356)=1564
2022-04-09 19:13:14,951 get_y(134)=882
2022-04-09 19:13:17,738 hide_notification()
2022-04-09 19:13:18,005 notification_closed(51, 1, ) server notification.close=True
2022-04-09 19:13:47,142 _process_notify_show(['notify_show', b'unix:abstract=/tmp/dbus-jsivYu .. ', b'Activate'), {b'desktop-entry': b'Firefox'}]) notifier=<xpra.platform.win32.win32_notifier.Win32_Notifier object at 0x0000019cfb3b7f10>, server_notifications=True
2022-04-09 19:13:47,153 notification actions=(b'default', b'Activate'), hints={b'desktop-entry': b'Firefox'}
2022-04-09 19:13:47,153 get_tray_window(Firefox)=Tray(0:Xpra)
2022-04-09 19:13:47,153 show_notify(..) using gtk fallback, GTK_NOTIFIER=False, tray=Tray(0:Xpra), getHWND=<bound method Win32Tray.getHWND of Tray(0:Xpra)>, actions=(b'default', b'Activate')
2022-04-09 19:13:47,169 Popup(<xpra.gtk_common.gtk_notifier.GTK_Notifier object at 0x0000019c81e47bb0>, 52, 'REDACTED (IRC)', '[notify]', (b'default', b'Activate'), None, -1, False)
2022-04-09 19:13:47,243 get_x(356)=1564
2022-04-09 19:13:47,263 get_y(134)=882
2022-04-09 19:13:50,059 hide_notification()
2022-04-09 19:13:50,074 notification_closed(52, 1, ) server notification.close=True
```

**Comment by totaam** [comment]
@jdstroy this log event didn't trigger the `Error parsing icon data for notification:`.

**Comment by jdstroy** [comment]
Odd.  Here's another time where it does that.  Seems to be very easily reproducible on the versions I'm running.

client stdout with `-d notify`:

```
2022-04-10 04:16:02,141 Xpra GTK3 client version 4.2.3-r3 64-bit
2022-04-10 04:16:02,204  running on Microsoft Windows 10
2022-04-10 04:16:08,592 GStreamer version 1.18.5 for Python 3.9.7 64-bit
2022-04-10 04:16:08,639 make_notifier() notifier classes: [<class 'xpra.platform.win32.win32_notifier.Win32_Notifier'>, <class 'xpra.gtk_common.gtk_notifier.GTK_Notifier'>, <class 'xpra.client.gtk3.gtk3_notifier.GTK3_Notifier'>]
2022-04-10 04:16:08,639 using notifier=<xpra.platform.win32.win32_notifier.Win32_Notifier object at 0x000001a2c7637f10>
2022-04-10 04:16:09,233 created named pipe 'Xpra\10744'
2022-04-10 04:16:09,672 keyboard layout code 0x409
2022-04-10 04:16:09,672 identified as 'United States - English' : us
2022-04-10 04:16:10,048 OpenGL_accelerate module loaded
2022-04-10 04:16:10,173 Using accelerated ArrayDatatype
2022-04-10 04:16:12,816 Warning: vendor 'Intel' is greylisted,
2022-04-10 04:16:12,816  you may want to turn off OpenGL if you encounter bugs
2022-04-10 04:16:13,443 OpenGL accelerate missing: numpy_formathandler
2022-04-10 04:16:15,759 OpenGL enabled with Intel(R) UHD Graphics 605
2022-04-10 04:16:16,635 Connected (version 2.0, client OpenSSH_8.2p1)
2022-04-10 04:16:17,088 loaded RSA private key from 'C:\Users\REDACTED/.ssh\id_rsa'
2022-04-10 04:16:17,245 Authentication (publickey) successful!
2022-04-10 04:16:17,965  keyboard settings: layout=us
2022-04-10 04:16:17,981  desktop size is 1920x1080 with 1 screen:
2022-04-10 04:16:17,981   Default (406x228 mm - DPI: 120x120) workarea: 1920x1020
2022-04-10 04:16:17,997     Digital Flat Panel (1024x768 60Hz) (344x194 mm - DPI: 142x141)
2022-04-10 04:16:20,907 enabled remote logging
2022-04-10 04:16:20,922 Xpra X11 seamless server version 4.4-r30923 64-bit
2022-04-10 04:16:20,922  running on Linux Ubuntu 20.04 focal
2022-04-10 04:16:20,954 Attached to ssh://REDACTED@REDACTED/21
2022-04-10 04:16:20,969  (press Control-C to detach)

2022-04-10 04:16:24,145 audio playback using 'opus' audio codec

(Xpra_cmd.exe:10744): Pango-WARNING **: 04:16:24.552: couldn't load font "DejaVu Serif Not-Rotated 59.796875", falling back to "Sans Not-Rotated 59.796875", expect ugly output.

(Xpra_cmd.exe:10744): Pango-WARNING **: 04:16:24.583: couldn't load font "URW Bookman L Not-Rotated 52.76171875", falling back to "Sans Not-Rotated 52.76171875", expect ugly output.
2022-04-10 04:16:25,340 running, 7 windows
2022-04-10 04:16:25,668 UI thread is now blocked
2022-04-10 04:16:27,780 server is not responding, drawing spinners over the windows
2022-04-10 04:16:28,327 server is OK again
2022-04-10 04:18:21,144 _process_notify_show(['notify_show', b'unix:abstract=/tmp/dbus-jsivYu .. ', b'Activate'), {b'desktop-entry': b'Firefox'}]) notifier=<xpra.platform.win32.win32_notifier.Win32_Notifier object at 0x000001a2c7637f10>, server_notifications=True
2022-04-10 04:18:21,175 notification actions=(b'default', b'Activate'), hints={b'desktop-entry': b'Firefox'}
2022-04-10 04:18:21,207 get_tray_window(Firefox)=Tray(0:Xpra)
2022-04-10 04:18:21,222 show_notify(..) using gtk fallback, GTK_NOTIFIER=False, tray=Tray(0:Xpra), getHWND=<bound method Win32Tray.getHWND of Tray(0:Xpra)>, actions=(b'default', b'Activate')
2022-04-10 04:18:21,238 monitors=1
2022-04-10 04:18:21,253 first monitor dimensions: 1920x1080
2022-04-10 04:18:21,285 our reduced dimensions: 1900x1016
2022-04-10 04:18:21,472 _process_notify_show(['notify_show', b'unix:abstract=/tmp/dbus-jsivYu .. ', b'Activate'), {b'desktop-entry': b'Firefox'}]) notifier=<xpra.platform.win32.win32_notifier.Win32_Notifier object at 0x000001a2c7637f10>, server_notifications=True
2022-04-10 04:18:21,488 notification actions=(b'default', b'Activate'), hints={b'desktop-entry': b'Firefox'}
2022-04-10 04:18:21,519 get_tray_window(Firefox)=Tray(0:Xpra)
2022-04-10 04:18:21,535 show_notify(..) using gtk fallback, GTK_NOTIFIER=False, tray=Tray(0:Xpra), getHWND=<bound method Win32Tray.getHWND of Tray(0:Xpra)>, actions=(b'default', b'Activate')
2022-04-10 04:18:21,550 Popup(<xpra.gtk_common.gtk_notifier.GTK_Notifier object at 0x000001a2cd8aa370>, 100, 'REDACTED (IRC)', '[notify]', (b'default', b'Activate'), None, -1, False)
2022-04-10 04:18:21,707 get_x(356)=1564
2022-04-10 04:18:21,738 get_y(134)=882
2022-04-10 04:18:21,816 Popup(<xpra.gtk_common.gtk_notifier.GTK_Notifier object at 0x000001a2cd8aa370>, 101, 'REDACTED (IRC)', '[notify]', (b'default', b'Activate'), None, -1, False)
2022-04-10 04:18:21,910 get_x(356)=1564
2022-04-10 04:18:21,910 get_y(134)=882
2022-04-10 04:18:24,585 hide_notification()
2022-04-10 04:18:24,600 reposition(0, <xpra.gtk_common.gtk_notifier.GTK_Notifier object at 0x000001a2cd8aa370>)
2022-04-10 04:18:24,600 get_x(356)=1564
2022-04-10 04:18:24,616 get_y(134)=882
2022-04-10 04:18:24,616 notification_closed(100, 1, ) server notification.close=True
2022-04-10 04:18:24,695 hide_notification()
2022-04-10 04:18:24,710 notification_closed(101, 1, ) server notification.close=True

2022-04-10 04:19:13,803 Python/GTK3 Client got signal SIGINT
2022-04-10 04:19:13,803 exiting

2022-04-10 04:19:13,803 Python/GTK3 Client got signal SIGINT
2022-04-10 04:19:13,818 exiting
2022-04-10 04:19:16,046 SSH EOF on stderr of run-xpra
2022-04-10 04:19:16,218 NotificationClient.cleanup() notifier=<xpra.platform.win32.win32_notifier.Win32_Notifier object at 0x000001a2c7637f10>
2022-04-10 04:19:16,421 NotificationClient.cleanup() notifier=None
2022-04-10 04:19:16,469 NotificationClient.cleanup() notifier=None
```

This is the surrounding context for the server's stdout (my apologies for the timezone difference; the server is one hour behind the client):

```
Apr 10 03:17:46 REDACTED xpra[1545430]: 2022-04-10 03:17:46,798 call_encode: 0
Apr 10 03:17:47 REDACTED xpra[1545430]: 2022-04-10 03:17:47,884 call_encode: 0
Apr 10 03:17:53 REDACTED dbus-daemon[1204]: [session uid=1002 pid=1204] Activating service name='org.freedesktop.thumbnails.Cache1' requested by ':1.2' (uid=1002 pid=1181 comm="/usr/libexec/tracker-miner-fs " label="unconfined")
Apr 10 03:17:53 REDACTED org.freedesktop.thumbnails.Cache1[2228975]: Registered thumbnailer /usr/bin/gdk-pixbuf-thumbnailer -s %s %u %o
Apr 10 03:17:53 REDACTED org.freedesktop.thumbnails.Cache1[2228975]: Registered thumbnailer /usr/bin/gdk-pixbuf-thumbnailer -s %s %u %o
Apr 10 03:17:53 REDACTED dbus-daemon[1204]: [session uid=1002 pid=1204] Successfully activated service 'org.freedesktop.thumbnails.Cache1'
Apr 10 03:17:57 REDACTED xpra[1545430]: 2022-04-10 03:17:57,138 call_encode: 0
Apr 10 03:18:02 REDACTED xpra[1545430]: 2022-04-10 03:18:02,884 call_encode: 0
Apr 10 03:18:12 REDACTED xpra[1545430]: 2022-04-10 03:18:12,140 call_encode: 0
Apr 10 03:18:17 REDACTED xpra[1545430]: 2022-04-10 03:18:17,885 call_encode: 0
Apr 10 03:18:21 REDACTED xpra[1545430]: 2022-04-10 03:18:21,454 Error parsing icon data for notification:
Apr 10 03:18:21 REDACTED xpra[1545430]: Traceback (most recent call last):
Apr 10 03:18:21 REDACTED xpra[1545430]:   File "/usr/lib/python3/dist-packages/xpra/notifications/common.py", line 26, in parse_image_data
Apr 10 03:18:21 REDACTED xpra[1545430]:     img = Image.frombytes(fmt, (width, height), pixels, "raw", rgb_format, rowstride)
Apr 10 03:18:21 REDACTED xpra[1545430]:   File "/usr/lib/python3/dist-packages/PIL/Image.py", line 2581, in frombytes
Apr 10 03:18:21 REDACTED xpra[1545430]:     im.frombytes(data, decoder_name, args)
Apr 10 03:18:21 REDACTED xpra[1545430]:   File "/usr/lib/python3/dist-packages/PIL/Image.py", line 769, in frombytes
Apr 10 03:18:21 REDACTED xpra[1545430]:     s = d.decode(data)
Apr 10 03:18:21 REDACTED xpra[1545430]: TypeError: a bytes-like object is required, not 'list'
Apr 10 03:18:21 REDACTED xpra[1545430]: 2022-04-10 03:18:21,454  a bytes-like object is required, not 'list'
Apr 10 03:18:21 REDACTED xpra[1545430]: 2022-04-10 03:18:21,480 Error parsing icon data for notification:
Apr 10 03:18:21 REDACTED xpra[1545430]: Traceback (most recent call last):
Apr 10 03:18:21 REDACTED xpra[1545430]:   File "/usr/lib/python3/dist-packages/xpra/notifications/common.py", line 26, in parse_image_data
Apr 10 03:18:21 REDACTED xpra[1545430]:     img = Image.frombytes(fmt, (width, height), pixels, "raw", rgb_format, rowstride)
Apr 10 03:18:21 REDACTED xpra[1545430]:   File "/usr/lib/python3/dist-packages/PIL/Image.py", line 2581, in frombytes
Apr 10 03:18:21 REDACTED xpra[1545430]:     im.frombytes(data, decoder_name, args)
Apr 10 03:18:21 REDACTED xpra[1545430]:   File "/usr/lib/python3/dist-packages/PIL/Image.py", line 769, in frombytes
Apr 10 03:18:21 REDACTED xpra[1545430]:     s = d.decode(data)
Apr 10 03:18:21 REDACTED xpra[1545430]: TypeError: a bytes-like object is required, not 'list'
Apr 10 03:18:21 REDACTED xpra[1545430]: 2022-04-10 03:18:21,480  a bytes-like object is required, not 'list'
Apr 10 03:18:21 REDACTED xpra[1545430]: 2022-04-10 03:18:21,492 call_encode: 0
Apr 10 03:18:21 REDACTED xpra[1545430]: 2022-04-10 03:18:21,509 client  15 @19.002 _process_notify_show(['notify_show', b'unix:abstract=/tmp/dbus-jsivYu .. ', b'Activate'), {b'desktop-entry': b'Firefox'}]) notifier=<xpra.platform.win32.win32_notifier.Win32_Notifier object at 0x000001a2c7637f10>, server_notifications=True
Apr 10 03:18:21 REDACTED xpra[1545430]: 2022-04-10 03:18:21,529 client  15 @19.024 notification actions=(b'default', b'Activate'), hints={b'desktop-entry': b'Firefox'}
Apr 10 03:18:21 REDACTED xpra[1545430]: 2022-04-10 03:18:21,565 client  15 @19.059 get_tray_window(Firefox)=Tray(0:Xpra)
Apr 10 03:18:21 REDACTED xpra[1545430]: 2022-04-10 03:18:21,585 client  15 @19.074 show_notify(..) using gtk fallback, GTK_NOTIFIER=False, tray=Tray(0:Xpra), getHWND=<bound method Win32Tray.getHWND of Tray(0:Xpra)>, actions=(b'default', b'Activate')
Apr 10 03:18:21 REDACTED xpra[1545430]: 2022-04-10 03:18:21,592 client  15 @19.092 monitors=1
Apr 10 03:18:21 REDACTED xpra[1545430]: 2022-04-10 03:18:21,629 client  15 @19.111 first monitor dimensions: 1920x1080
Apr 10 03:18:21 REDACTED xpra[1545430]: 2022-04-10 03:18:21,712 client  15 @19.143 our reduced dimensions: 1900x1016
Apr 10 03:18:21 REDACTED xpra[1545430]: 2022-04-10 03:18:21,828 client  15 @19.326 _process_notify_show(['notify_show', b'unix:abstract=/tmp/dbus-jsivYu .. ', b'Activate'), {b'desktop-entry': b'Firefox'}]) notifier=<xpra.platform.win32.win32_notifier.Win32_Notifier object at 0x000001a2c7637f10>, server_notifications=True
Apr 10 03:18:21 REDACTED xpra[1545430]: 2022-04-10 03:18:21,838 client  15 @19.343 notification actions=(b'default', b'Activate'), hints={b'desktop-entry': b'Firefox'}
Apr 10 03:18:21 REDACTED xpra[1545430]: 2022-04-10 03:18:21,898 client  15 @19.378 get_tray_window(Firefox)=Tray(0:Xpra)
Apr 10 03:18:21 REDACTED xpra[1545430]: 2022-04-10 03:18:21,910 client  15 @19.390 show_notify(..) using gtk fallback, GTK_NOTIFIER=False, tray=Tray(0:Xpra), getHWND=<bound method Win32Tray.getHWND of Tray(0:Xpra)>, actions=(b'default', b'Activate')
Apr 10 03:18:21 REDACTED xpra[1545430]: 2022-04-10 03:18:21,941 client  15 @19.400 Popup(<xpra.gtk_common.gtk_notifier.GTK_Notifier object at 0x000001a2cd8aa370>, 100, 'REDACTED (IRC)', '[notify]', (b'default', b'Activate'), None, -1, False)
Apr 10 03:18:22 REDACTED xpra[1545430]: 2022-04-10 03:18:22,055 client  15 @19.554 get_x(356)=1564
Apr 10 03:18:22 REDACTED xpra[1545430]: 2022-04-10 03:18:22,083 client  15 @19.587 get_y(134)=882
Apr 10 03:18:22 REDACTED xpra[1545430]: 2022-04-10 03:18:22,180 client  15 @19.674 Popup(<xpra.gtk_common.gtk_notifier.GTK_Notifier object at 0x000001a2cd8aa370>, 101, 'REDACTED (IRC)', '[notify]', (b'default', b'Activate'), None, -1, False)
Apr 10 03:18:22 REDACTED xpra[1545430]: 2022-04-10 03:18:22,258 client  15 @19.756 get_x(356)=1564
Apr 10 03:18:22 REDACTED xpra[1545430]: 2022-04-10 03:18:22,273 client  15 @19.766 get_y(134)=882
Apr 10 03:18:25 REDACTED xpra[1545430]: 2022-04-10 03:18:25,040 client  15 @22.431 hide_notification()
Apr 10 03:18:25 REDACTED xpra[1545430]: 2022-04-10 03:18:25,040 client  15 @22.452 reposition(0, <xpra.gtk_common.gtk_notifier.GTK_Notifier object at 0x000001a2cd8aa370>)
Apr 10 03:18:25 REDACTED xpra[1545430]: 2022-04-10 03:18:25,041 client  15 @22.457 get_x(356)=1564
Apr 10 03:18:25 REDACTED xpra[1545430]: 2022-04-10 03:18:25,041 client  15 @22.468 get_y(134)=882
Apr 10 03:18:25 REDACTED xpra[1545430]: 2022-04-10 03:18:25,041 client  15 @22.472 notification_closed(100, 1, ) server notification.close=True
Apr 10 03:18:25 REDACTED xpra[1545430]: 2022-04-10 03:18:25,049 client  15 @22.541 hide_notification()
Apr 10 03:18:25 REDACTED xpra[1545430]: 2022-04-10 03:18:25,070 client  15 @22.564 notification_closed(101, 1, ) server notification.close=True
Apr 10 03:18:27 REDACTED xpra[1545430]: 2022-04-10 03:18:27,141 call_encode: 0
Apr 10 03:18:32 REDACTED xpra[1545430]: 2022-04-10 03:18:32,884 call_encode: 0
```

**Comment by totaam** [comment]
Gotcha!
The only location calling `parse_image_data` is:
https://github.com/Xpra-org/xpra/blob/7fe24307dfddf78094320f3dabe962641e9aeafc/xpra/dbus/notifications_forwarder.py#L88-L97

As per [Desktop Notifications Specification : Icons and Images](https://specifications.freedesktop.org/notification-spec/notification-spec-latest.html#icons-and-images): the pixel data is an array of bytes.

So perhaps this code never worked properly? The trivial commit above should fix that.

**Comment by jdstroy** [comment]
If you make an ARM64 build for Ubuntu Focal arm64, I will be happy to test it out.

**Comment by totaam** [comment]
Done. Focal arm64 beta builds: https://xpra.org/beta/focal/main/binary-arm64/
(r31167 or later)

**Comment by jdstroy** [comment]
Looks good to me.  I no longer get that error, and notifications still appear to be working.
