### ISSUE TITLE
`xpra` repository for CentOS 8 yields 403 / Forbidden

### ISSUE THREAD

**Issue by olifre** [Xpra-org/xpra#3529]
(I hope repo issues are also correct to report here)

**Describe the bug**
Trying to access:
https://xpra.org/dists/CentOS/8/x86_64/repodata/repomd.xml
yields a 403 error (Forbidden). 

**To Reproduce**
1. `wget -O /etc/yum.repos.d/xpra.repo https://xpra.org/repos/CentOS/xpra.repo`
2. `dnf -y install xpra xpra-html5`

Output:
```
Errors during downloading metadata for repository 'xpra':
  - Status code: 403 for https://xpra.org/dists/CentOS/8/x86_64/repodata/repomd.xml (IP: 78.129.163.65)
Error: Failed to download metadata for repo 'xpra': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

**System Information (please complete the following information):**
 - OS: RockyLinux 8 (but should fail with any RedHat-like distro in version 8)

**Additional context**
Checking:
https://xpra.org/dists/CentOS/
it seems that `8.2` and `8.3` directories are still visible, but the symbolic link `8` pointing to the latest release is invisible.

**Comment by totaam** [comment]
Thanks for the report.
Fixed.

You're right: `8` was pointing to `8.5` which isn't available yet. Now restored to `8.4`.

**Comment by olifre** [comment]
Thanks, @totaam !
Sadly, I still get:
```
curl https://xpra.org/dists/CentOS/8/x86_64/repodata/repomd.xml
...
<title>403 Forbidden</title>
```
Is there maybe a permission issue on the `8` link?

**Comment by totaam** [comment]
My bad, I ran the repo scripts again after that (for something unrelated) and re-created the broken symlink!

**Comment by olifre** [comment]
Thanks, no problem — I can confirm it's fixed now :+1: .
