### ISSUE TITLE
xpra server crash when running an electron program

### ISSUE THREAD

**Issue by tou2** [Xpra-org/xpra#3530]
Unity hub program crashes xpra server intermittently when I open the Unity hub program. What I see is all the open windows for other programs disappear suddenly after I click on unity hub and then its window frame.
Sometimes it works the whole day and other times never.

**To Reproduce**
1. xpra start --forward-xdg-open=off --bind-tcp=0.0.0.0:10000 --html=on -d all
2. Running Unity Hub after installing. Sometimes it works and other time it crashes the xpra server.

**System Information (please complete the following information):**
 - Server OS: Ubuntu 20.04
 - Client OS: HTML5
 - Xpra Server Version v4.3.2-r0
 - Xpra Client Version 4.5.2

**Additional context**
I get this error when the crash happens in the debug file:

```
(Xpra:538): Gdk-ERROR **: 13:09:28.023: The program 'Xpra' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 2862 error_code 3 request_code 12 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.) 
```

**Comment by totaam** [comment]
Can you get a gdb backtrace? (see https://github.com/Xpra-org/xpra/wiki/Debugging#gdb and add a breakpoint on `gdk_x_error`)
Or post the log file since you already had `-d all`?

There may be more X11 related info with:
```shell
XPRA_X11_DEBUG_EVENTS=all xpra start -d all ...
```

**Comment by tou2** [comment]
[server.log](https://github.com/Xpra-org/xpra/files/8548639/server.log)

This is the debug all file.

**Comment by totaam** [comment]
Any idea what might have caused this:
```
2022-04-23 21:16:14,716 BUG? video for tray - don't use video region!
```

The last entry before the crash is:
```
2022-04-23 21:16:14,731 XShmImageWrapper(RGBA: 0, 0, 64, 64).free_pixels() pixels=0x7f2564022380
2022-04-23 21:16:14,731 XShmWrapper.free_image_callback() closed=0, new ref_count=0
2022-04-23 21:16:14,731 XShmImageWrapper.free() done for XShmImageWrapper(RGBA: 0, 0, 64, 64), callback fired=True
```

Can you run with 4c192ebbc03ac966a8076f25a01846a284fc3cc9 applied and see if anything new comes up in the server log when it crashes?

Also, you may be able to workaround the problem by starting your server with `--video-encoders=none --csc-modules=none`.

**Comment by totaam** [comment]
I think I'm onto something:
```
 XShmWrapper.__dealloc__() ref_count=0
 XShmWrapper.free() has_shm=False, image=0x0, shmid=-0x1
 Error: unmanaged X11 context
  XShmWrapper.free()
    File "/usr/bin/xpra", line 10, in <module>
      sys.exit(main(sys.argv[0], sys.argv))
    File "/usr/lib64/python3.9/site-packages/xpra/scripts/main.py", line 143, in main
      return run_mode(script_file, cmdline, err, options, args, mode, defaults)
    File "/usr/lib64/python3.9/site-packages/xpra/scripts/main.py", line 417, in run_mode
      return do_run_mode(script_file, cmdline, error_cb, options, args, mode, defaults)
    File "/usr/lib64/python3.9/site-packages/xpra/scripts/main.py", line 452, in do_run_mode
      return run_server(script_file, cmdline, error_cb, options, args, mode, defaults)
    File "/usr/lib64/python3.9/site-packages/xpra/scripts/main.py", line 1777, in run_server
      return do_run_server(script_file, cmdline, error_cb, options, args, mode, display, defaults)
    File "/usr/lib64/python3.9/site-packages/xpra/scripts/server.py", line 673, in do_run_server
      return _do_run_server(script_file, cmdline,
    File "/usr/lib64/python3.9/site-packages/xpra/scripts/server.py", line 1421, in _do_run_server
      r = app.run()
    File "/usr/lib64/python3.9/site-packages/xpra/server/server_core.py", line 438, in run
      self.do_run()
    File "/usr/lib64/python3.9/site-packages/xpra/server/gtk_server_base.py", line 128, in do_run
      Gtk.main()
    File "/usr/lib/python3.9/site-packages/gi/overrides/Gtk.py", line 1680, in main
      return _Gtk_main(*args, **kwargs)
 XShmWrapper.free_image_callback() closed=0, new ref_count=0
```
We may end up freeing the XShm image from a code path that does not guard against X11 errors.
If the application closes the window whilst we are freeing the image, this could cause a crash.

**Comment by tou2** [comment]
Here are two server log files using #4c192eb 
This time xpra server crashed: [newCrash.log](https://github.com/Xpra-org/xpra/files/8549902/newCrash.log)
This time Unity worked and no crash happened: [WorkLog.log](https://github.com/Xpra-org/xpra/files/8549903/WorkLog.log)

Another thing I also noticed, the times when Unity works and don't crash xpra. When I click on the other window boarders and Unity is on right behind, it brings the unity window to the from. It only happens with Unity.

![image](https://user-images.githubusercontent.com/706122/164982324-18c38bec-8354-415d-99d3-7740ad3356c5.png)


![image](https://user-images.githubusercontent.com/706122/164982360-77548b4c-38da-4b52-99b0-64bd185725f1.png)

**Comment by tou2** [comment]
The files attached above are using `xpra start --forward-xdg-open=off --bind-tcp=0.0.0.0:10000 --html=on -d all`

**Comment by totaam** [comment]
The commit above may be the one that fixes this crash, whereas the previous 2 commits were just things I found along the way.

At least I am no longer able to trigger the `unmanaged X11 context` error in `XShmWrapper`.

@tou2 please try `4.4-r31233` or later.

**Comment by tou2** [comment]
Unity crashed xpra server with v4.4-r31227 

```
xpra --version 
xpra v4.4-r31227 (g35a6aee34)
```

[server.log](https://github.com/Xpra-org/xpra/files/8565890/server.log)

**Comment by totaam** [comment]
I have found one more potential problem: I had initially dismissed the `SystemTrayWindowModel` events near the crash site, but perhaps it is the system tray window which is causing the `BadWindow` error somewhere unexpected.
In which case, the commit just above may help - though I somehow doubt it would be this simple to fix.

@tou2 does r31233 or later help?

**Comment by tou2** [comment]
I have just deployed the master version and It same problem.

[server.log](https://github.com/Xpra-org/xpra/files/8574572/server.log)

**Comment by totaam** [comment]
So, I installed `UnityHub.appimage` and connected more than 10 times from both MS Windows 10 and a browser via the html5 client. It didn't crash once.

I did find something weird though: `unityhub-bin` creates a 1x1 `InputOutput` override-redirect window that it places at -200,-200 (offscreen).
As per https://github.com/Xpra-org/xpra/wiki/Reporting-Bugs - `xpra info` is always useful to have and would have shown this from the start.
This is probably the one that is causing the problem. Are they trying to catch all user input with this?

Anyway, the commit above skips sending pixels for such windows.
Ideally, we would ignore the window altogether - but that's much harder to do: some applications may create windows offscreen and later re-configure them onscreen... we can't just ignore them permanently.

**Comment by tou2** [comment]
Good news, I think the problem is fixed but after I deployed the master html5 version on the server that was serving the html client. 
I didn't track down what was wrong yet but the 2 main differences is that it was not the master branch but latest stable and I had modified the xpra html5 tray and removed the dropdown menu.
Now everything works after I activated the full tray and the html master branch.

**Comment by totaam** [comment]
> ... but latest stable and I had modified the xpra html5 tray and removed the dropdown menu

Wait, what!?

So this whole time I stood zero chance of actually reproducing those conditions.

The underlying bug is a server bug too, so it's likely not fixed at all.
No client should be able to trigger an X11 server crash.

**Comment by tou2** [comment]
The one thing that happens now but rarely is the some windows would open with the frame only and in center I see behind and I have to reboot to fix it. I am not sure if it is related but it is rare.

**Comment by totaam** [comment]
Please include the changes you made to the html5 client so that I can reproduce the problem.

**Comment by totaam** [comment]
Another X11 server crash has just been fixed: #3537

Without those html5 modifications, I cannot verify if this is related or not...

**Comment by tou2** [comment]
I am sorry for the delay, I will upload the client files that was causing the problems. I will ping my friend that was working on that part. @Mohamedemad4.

**Comment by tou2** [comment]
Attached is the html5 I was using with the modifications:
 
[public.zip](https://github.com/Xpra-org/xpra/files/8656248/public.zip)

**Comment by totaam** [comment]
This is a zip file of an older version of the code - I don't see any noticeable differences with master, just missing fixes.
Please provide a diff, a branch, anything that shows the differences.

**Comment by tou2** [comment]
This is zip file is copied from what I had deployed. I will try to put it in a new github repo and create a diff with the current html5

**Comment by totaam** [comment]
Not heard back, I assume that this is already fixed.
