### ISSUE TITLE
xpra doesn't have a tray icon under Wayland with KWin

### ISSUE THREAD

**Issue by allo-** [Xpra-org/xpra#3789]
**Describe the bug**
xpra does not show its tray icon in a KDE Wayland session

**To Reproduce**
1. Run a KDE Wayland session
2. Connect from a terminal to an xpra server

**Expected**
A tray icon with the functions that are provided when using X11 (Launch applications, enable/disable features like forwarding clipboard, sound, etc.)

**Actual Behavior**
No tray icon is visible.

**System Information (please complete the following information):**
 - Server OS: Debian stable
 - Client OS: Debian testing
 - Xpra Server Version: 4.4.3-r0-1
 - Xpra Client Version: 5.0-r32793-1

**Comment by totaam** [comment]
> I hope I don't need gnome shell extensions for a KDE session as they would probably install almost all of gnome as dependencies.

And this exactly why we don't install them as _Recommended_ dependencies: https://github.com/Xpra-org/xpra/issues/2979#issuecomment-765553745

**Comment by allo-** [comment]
> And this exactly why we don't install them as Recommended dependencies: https://github.com/Xpra-org/xpra/issues/2979#issuecomment-765553745

So am I right that I do not need gnome-shell packages?
Or is this another thing where things are mixed together which should be separated?

**Comment by totaam** [comment]
@allo- I have no idea which package you may need to make it work under KDE, sorry.

**Comment by totaam** [comment]
If you find out which packages are needed to make the system tray work under KDE, let us know!

**Comment by allo-** [comment]
I wonder why you're closing this. My KDE Wayland session has no problems with the trayicons of most programs, but xpra silently does not show any. So I would suppose this is a xpra bug or at least something xpra should have a workaround for if it is some chaos with new Wayland libraries, gnome specific implementations and so on.

I wouldn't think there is a package for KDE missing, or at least I would not know what additional package should be needed. It *is* quite possible that KDE still have bugs as well (and KDE Wayland is not my primary session), but I do not see an obvious indication of that either.

So what do you suppose to be a missing package? Some libindicator(?) to Wayland middleware? Or would it need a new python trayicon library and you don't know yet which? I would suppose, that it should "just work" and if it does not it is a bug somewhere.

I see that Wayland may not be high-priority, but I am not sure if this should be closed and probably one should test other Wayland desktops as well when it is desktop specific.

**Comment by totaam** [comment]
Please post the client's output when running with `-d tray`.
Then maybe we can figure out which backend it is using and perhaps there is a better one we should be using on your particular DE flavor.

**Comment by allo-** [comment]
Will do later. I am also willing to do more detailed tests for experimental patches and so on.

**Comment by totaam** [comment]
See also #3342, #476 and #406

**Comment by totaam** [comment]
Your log sample is incomplete and is missing the crucial part:
https://github.com/Xpra-org/xpra/blob/e8b97243e58ba0f6d03074e1d0bdc9c2d0fc9f9b/xpra/platform/xposix/gui.py#L123-L139

This would have shown us why you end up with the `GTKStatusIconTray` rather than the `AppindicatorTray`.

To figure it out, you could also just run this file from a command line:
```shell
python3 /usr/lib/*/*/xpra/platform/xposix/appindicator_tray.py
```

**Comment by allo-** [comment]
> python3 /usr/lib/*/*/xpra/platform/xposix/appindicator_tray.py

Tested under X11 (will see Wayland later) and there seems to be something missing:

```
$ python3 /usr/lib/*/*/xpra/platform/xposix/appindicator_tray.py
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xpra/platform/xposix/appindicator_tray.py", line 26, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available
```

Looks like I may have to test different libindicator packages. `gir1.2-ayatanaappindicator-0.1` is not installed but looks like it may be the right one because of the version, but it would uninstall `libappindicator1`. A seemingly outdated recommendation is `gir1.2-appindicator3-0.1` what doesn't exist in current Debian testing.

**Comment by totaam** [comment]
This was changed 6 months ago: 45ba9b27d5269cfe2f10e6c227703b92f78396d8, we recommend one or the other:
https://github.com/Xpra-org/xpra/blob/36ff920a309604f33c8edea824b968719d7ded7a/packaging/debian/xpra/control#L141

I've changed it again to recommend both packages, so you should end up with one that works - no matter what distribution / version you have.
I have no idea why the new packages doesn't provide the old name. Answer on a postcard.

**Comment by allo-** [comment]
```
E: Package 'gir1.2-ayatanaappindicator3' has no installation candidate
```

and

```
gir1.2-ayatanaappindicator3-0.1 is already the newest version (0.5.92-1).
```

but for `gir1.2-ayatanaappindicator-0.1`

```
The following additional packages will be installed:
  gir1.2-gtk-2.0 libayatana-appindicator1 libayatana-indicator7
The following packages will be REMOVED:
  libappindicator1
The following NEW packages will be installed:
  gir1.2-ayatanaappindicator-0.1 gir1.2-gtk-2.0 libayatana-appindicator1 libayatana-indicator7
```

**Comment by totaam** [comment]
`gir1.2-ayatanaappindicator-0.1` is the GTK2 version - we don't need that.

But of course, Debian uses two version numbers as part of the package name. Because reasons.
Although the debian package search does manage to find `gir1.2-ayatanaappindicator3` without problems..
* bookworm: https://packages.debian.org/bookworm/gir1.2-ayatanaappindicator3-0.1
* bullseye: https://packages.debian.org/bullseye/gir1.2-ayatanaappindicator3-0.1

---

@allo- more importantly: does this make any difference, is xpra choosing the `appindicator` backend now?
If not, what does the log file say?

**Comment by allo-** [comment]
I will test Wayland later. Currently the plasma wayland session is having its own problems with massive lag for the input devices, I do not know if some Wayland libraries or the plasma/kwin update in the meantime are the problem. Sometimes I think the whole xorg/freedesktop stuff is causing massive headaches.

Yesterday I still tested the tray issue on a massive laggy session because I promised to provide the log (and probably the log got cut off because I had to pipe it into a log file and kill the session afterward). I think I can test later when I have time where I do not need a working desktop at the same time.

**Comment by totaam** [comment]
You also need the commit above (because they've changed the name of the bindings.. for reasons) and then you also need to enable appindicator in `gnome-tweaks`:
![fix-gnome-tray](https://user-images.githubusercontent.com/1049737/225882330-b7849bb3-87a5-4144-8574-7331410b2911.png)

They sure know how to make it hard for applications to integrate into the desktop.
And the end result is still "meh": appindicator is limited to ugly menus so this is nowhere near as user-friendly as the tray menu we have on all the other platforms. Better than nothing I guess?

**Comment by allo-** [comment]
Thank you, it works now. It at least shows the tray icon, with the currently unusable input I didn't try the menu but I don't see why it shouldn't work. Gladly I did not need to use gnome-tweaks for KDE. The X11 session now also seems to use AppIndicator instead of Gtk Trayicons.

**Comment by allo-** [comment]
I have a strange side-effect: The menu item "clipboard" now does not have a submenu.

I thought it would be an independent issue, but when I change `AyatanaAppIndicator3` to an invalid string again, the menu is there.

**Comment by totaam** [comment]
> but when I change `AyatanaAppIndicator3` to an invalid string again, the menu is there.

I saw this behaviour once, but now the clipboard menu is shown every single time - looks like a fluke.
I think we can close this ticket.

**Comment by totaam** [comment]
This caused a regression, fixed in 9613d1faf3ea8d49830a6aef1ee4c3421dfd7928

**Comment by allo-** [comment]
#3800 is still an issue here, even when applying https://github.com/Xpra-org/xpra/commit/9613d1faf3ea8d49830a6aef1ee4c3421dfd7928. I think it should be discussed in the other bug, though.

**Comment by totaam** [comment]
@alexdelorenzo please bug your mantainer, this should be included as part of the xpra client's dependencies.
