### ISSUE TITLE
mouse wheel scrolling up and down also moves left and right

### ISSUE THREAD

**Issue by infcs** [Xpra-org/xpra#4689]
Hi,

first I'd like to say thank you for xpra! It is great software!

Now to the problem I am facing this morning.

**Describe the bug**
When using the mouse scroll wheel to scroll up and down the contents of windows it also
scrolls to the left and right. Scrolling down moves down and right. Scrolling up moves up and left.

I tested this in kmail, kwrite and firefox. I could not find any  application where this is not happening.

It does not happen if I use the scroll wheel locally on the client machine. E.g. kwrite running locally on 
my host without xpra. It happens only if running the applications via xpra.

It did not happen with xpra version 6.3.3.

**To Reproduce**
1. `/usr/bin/xpra --no-daemon start --start /home/cneerf2m/.xinitrc`
2. `/usr/bin/xpra attach vsock://4:10000/ -d mmap --mmap=/dev/shm/shmem-office --title=@title@ on @server-machine@ --speaker=off --system-tray=yes --session-name=office --border=yellow,2 --dpi=96 --tray-icon=xpra_office.png --clipboard-direction=to-client`
3. use the scroll wheel in an application which has vertical and horizontal scroll bars

xpra config on server:
```
mmap=/sys/devices/pci0000:00/0000:00:02.0/0000:01:00.0/0000:02:01.0/resource2_wc
webcam=no
start-new-commands=yes
html=off
mdns=no
bind-vsock=auto:10000
clipboard-direction=to-client
start-env=QT_QPA_PLATFORMTHEME=qt5ct
```
**System Information (please complete the following information):**
 - Server OS: Debian Bookworm
 - Client OS: Debian Bookworm
 - Xpra Server Version 6.3.4
 - Xpra Client Version 6.3.4

**Additional context**
The xpra server is running in a virtual machine which is running on the same host as the xpra client.
The xpra client is using a vsocket and a shared memory file (which is not working since some time, but that is different story; vsocket is working).

I tried xev from the host and from within the virtual machine. Both show the same events for mouse scrolling;
button 5 for scrolling down and button 4 for scrolling up.

Kind regards
Chris

**Comment by totaam** [comment]
Oh, it's been buggy for a long time it seems.
The commit above should fix that.

**Comment by kugel-** [comment]
The problem remains in 6.3.5 (same version on client and server). To my understanding 6.3.5 should contain this fix?

**Comment by totaam** [comment]
@kugel- Yes, the 6.3.x version looks correct to me:
https://github.com/Xpra-org/xpra/blob/86216fa2e4f170effcdcae99604881f140147842/xpra/client/mixins/windows.py#L562-L575

The handler for non-smooth events is simpler:
https://github.com/Xpra-org/xpra/blob/a8e7a7c6a7edb332ee8fded445fc581e1f78cc91/xpra/client/gtk3/window/pointer.py#L293-L298 and just sends pairs of press+unpress button events for a single button.

Running `xev` in a 6.3.5 session, I only see the same press+unpress event for button 5 (down) or 4 (up).

Please include your client's `-d mouse` log for just one scroll event.

**Comment by kugel-** [comment]
There's a lot of output just by moving the mouse and scrolling becomes completely defunct. I tried to capture one tick of the mouse wheel (it does output something, yet the view doesn't actually scroll, in this case the application is Geany).

FWIW, this is also happening with local xpra (attaching to the same machine).

```
2025-11-05 09:15:38,924 wheel_event(-1, 2, 0.0, -0.0) new deltas=0.375,-0.375
2025-11-05 09:15:38,932 send_wheel_deltas(-1, 2, 7, 0.5, (2545, 716, 625, 328), None) precise wheel=False, modifiers=['mod2'], pointer=(2545, 716, 625, 328)
2025-11-05 09:15:38,933 send_wheel_deltas(-1, 2, 5, -0.5, (2545, 716, 625, 328), None) precise wheel=False, modifiers=['mod2'], pointer=(2545, 716, 625, 328)
2025-11-05 09:15:38,933 wheel_event(-1, 2, 0.125, -0.125) new deltas=0.5,-0.5
2025-11-05 09:15:38,942 send_wheel_deltas(-1, 2, 7, 0.625, (2545, 716, 625, 328), None) precise wheel=False, modifiers=['mod2'], pointer=(2545, 716, 625, 328)
2025-11-05 09:15:38,942 button packet: ['pointer-button', -1, 0, 2, 7, True, (2545, 716, 625, 328), {'modifiers': ['mod2'], 'buttons': [], 'raw-buttons': ()}]
2025-11-05 09:15:38,942 button packet: ['pointer-button', -1, 0, 2, 7, False, (2545, 716, 625, 328), {'modifiers': ['mod2'], 'buttons': [], 'raw-buttons': ()}]
2025-11-05 09:15:38,943 send_wheel_deltas(-1, 2, 5, -0.625, (2545, 716, 625, 328), None) precise wheel=False, modifiers=['mod2'], pointer=(2545, 716, 625, 328)
2025-11-05 09:15:38,944 button packet: ['pointer-button', -1, 0, 2, 5, True, (2545, 716, 625, 328), {'modifiers': ['mod2'], 'buttons': [], 'raw-buttons': ()}]
2025-11-05 09:15:38,944 button packet: ['pointer-button', -1, 0, 2, 5, False, (2545, 716, 625, 328), {'modifiers': ['mod2'], 'buttons': [], 'raw-buttons': ()}]
2025-11-05 09:15:38,944 wheel_event(-1, 2, 0.125, -0.125) new deltas=-0.375,0.375
2025-11-05 09:15:38,950 send_wheel_deltas(-1, 2, 6, -0.25, (2545, 716, 625, 328), None) precise wheel=False, modifiers=['mod2'], pointer=(2545, 716, 625, 328)
2025-11-05 09:15:38,950 send_wheel_deltas(-1, 2, 4, 0.25, (2545, 716, 625, 328), None) precise wheel=False, modifiers=['mod2'], pointer=(2545, 716, 625, 328)
2025-11-05 09:15:38,950 wheel_event(-1, 2, 0.125, -0.125) new deltas=-0.25,0.25
2025-11-05 09:15:38,958 send_wheel_deltas(-1, 2, 6, -0.125, (2545, 716, 625, 328), None) precise wheel=False, modifiers=['mod2'], pointer=(2545, 716, 625, 328)
2025-11-05 09:15:38,958 send_wheel_deltas(-1, 2, 4, 0.125, (2545, 716, 625, 328), None) precise wheel=False, modifiers=['mod2'], pointer=(2545, 716, 625, 328)
2025-11-05 09:15:38,959 wheel_event(-1, 2, 0.125, -0.125) new deltas=-0.125,0.125
2025-11-05 09:15:38,984 send_wheel_deltas(-1, 2, 6, 0.0, (2545, 716, 625, 328), None) precise wheel=False, modifiers=['mod2'], pointer=(2545, 716, 625, 328)
2025-11-05 09:15:38,984 send_wheel_deltas(-1, 2, 5, 0.0, (2545, 716, 625, 328), None) precise wheel=False, modifiers=['mod2'], pointer=(2545, 716, 625, 328)
2025-11-05 09:15:38,984 wheel_event(-1, 2, 0.125, -0.125) new deltas=0.0,0.0
2025-11-05 09:15:39,024 send_wheel_deltas(-1, 2, 7, 0.125, (2545, 716, 625, 328), None) precise wheel=False, modifiers=['mod2'], pointer=(2545, 716, 625, 328)
2025-11-05 09:15:39,025 send_wheel_deltas(-1, 2, 5, -0.125, (2545, 716, 625, 328), None) precise wheel=False, modifiers=['mod2'], pointer=(2545, 716, 625, 328)
2025-11-05 09:15:39,026 wheel_event(-1, 2, 0.125, -0.125) new deltas=0.125,-0.125
```

**Comment by kugel-** [comment]
> and scrolling becomes completely defunct

I could repair this by restarting the server. Now scrolling works again with and without `-d mouse` on the client.

There is a separate, but maybe related, issue: ctrl+mouse wheel changes tabs in Geany, instead of horizontal scrolling. This happens only under xpra. If I start Geany directly it works as expected. Should I file a new issue for this?

**Comment by totaam** [comment]
Found it: the backport in e376b9f40174be2ee4655f6713ceaf8eb7371157 broke it (the original change for git master was fine: d65e5ced987822545e4fd0f95fec50d67622a56f), now fixed in 5046f028b94e71dcb297380c9f32919a82d222ec.

Sorry it's taken so long to identify it.

Looks like I will need to make another 6.3.x release soon..
Until then, you can disable smooth scrolling to avoid the problematic code with `XPRA_SMOOTH_SCROLL=0`.

---

As for ctrl + mousewheel doing something special, that's up to the application I believe - is this related to this issue?

**Comment by kugel-** [comment]
> As for ctrl + mousewheel doing something special, that's up to the application I believe - is this related to this issue?

Don't know if it's related, might be if xpra is sending wrong events.

I don't think it's an application thing. Geany behaves correctly under native X11 and wrongly under xpra. I can confirm this on the same machine (native vs local xpra).

**Comment by kugel-** [comment]
Seems related. `XPRA_SMOOTH_SCROLL=0` fixes "ctrl+mouse wheel" as well.

**Comment by unisons** [comment]
XPRA_SMOOTH_SCROLL=0 is working for android studio app but not for qt6 base application such perforce visual client.

**Comment by kugel-** [comment]
Both problems (horizontal scrolling and tab change in Geany) are fixed in 6.3.6. Thank you!
